
#ifndef OBLIVIOUS_JOIN_SGX_CODE_DEBUG
//#define OBLIVIOUS_JOIN_SGX_CODE_DEBUG
#endif

#ifndef OBLIVIOUS_JOIN_SGX_CODE_VERBOSE
//#define OBLIVIOUS_JOIN_SGX_CODE_VERBOSE
#endif

#ifndef FLORIANDATA
#define FLORIANDATA
#endif